name: "customer_journey_view"
version: "1.0.0"
config-version: 2

profile: "customer_journey_view"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

seeds:
  customer_journey_view: 

models:
  customer_journey_view:
    example:
      materialized: view
