name: "customer_journey_view"
version: "1.0.0"
config-version: 2

profile: "customer_journey_view"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  customer_journey_view:
    marts:
      core:
        schema: core_mart
        materialized: table

    staging:
      ecommerce:
        schema: staging
        materialized: view
        +persist_docs:
          relation: true
          columns: true
